# Generated by Django 5.1 on 2024-10-08 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0002_car_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='my_first_app.car')),
            ],
        ),
    ]
