# Generated by Django 5.1 on 2024-10-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_first_app', '0004_author_publisher_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
    ]
